name: Run unitest on push and pull request

on:
  push:
  pull_request:

jobs:
  unitest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14.15'
    - run: |
        ./unitest.sh
    - name: openapi-lint 
      uses: mbowman100/swagger-validator-action@master
      with:
        files: controller/api/apis.yaml
